server: 
  port: 9004
spring: 
  application:  
    name: tensquare-artical #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.66.136:3306/tensquare_article?useUnicode=true&amp;characterEncoding=UTF8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.66.136
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
